import { MIN_QUALITY, QUALITY_STEP, MAX_QUALITY_ITERATIONS } from './compressionConstants.js';
import type { CompressedImageResult } from './types.js';

/**
 * The worker script is authored as a plain JS string, not generated by bundling/importing a
 * separate `.ts` file (`new Worker(new URL(...))`) or by `.toString()`-stringifying a shared TS
 * function. `tsup.config.ts` ships one flat file per subpath with no chunking, so a real second
 * worker file would need a new build entry, a new `package.json#exports` key, and reliance on the
 * *consuming app's* bundler correctly resolving a relative worker URL — exactly the kind of
 * bundler-specific coupling this codebase avoids elsewhere (structural shapes over real
 * dependencies in `asyncStorageAdapter.ts`/`localStorageAdapter.ts`, "no dependency" comments
 * throughout `media/`). Stringifying a shared TS function via `Function.prototype.toString()` was
 * also considered and rejected: it depends on downstream tooling preserving reflectable source
 * faithfully, which is a real (if usually-safe) footgun class that's hard to eyeball-verify.
 *
 * The only duplication this creates is the small dimension/quality-search algorithm below, which
 * mirrors `computeTargetDimensions()`/the quality loop in `compressImage.ts` — keep the two in
 * sync if either changes. `MIN_QUALITY`/`QUALITY_STEP`/`MAX_QUALITY_ITERATIONS` themselves are
 * NOT duplicated (interpolated from `compressionConstants.ts` below), only the surrounding JS is.
 */
const WORKER_SOURCE = `
self.onmessage = async (event) => {
  const req = event.data;
  try {
    const bitmap = await createImageBitmap(req.file, { imageOrientation: 'from-image' });
    let width = bitmap.width;
    let height = bitmap.height;
    if (width > req.maxWidth) {
      height = Math.round((height * req.maxWidth) / width);
      width = req.maxWidth;
    }
    if (req.maxHeight && height > req.maxHeight) {
      width = Math.round((width * req.maxHeight) / height);
      height = req.maxHeight;
    }

    const canvas = new OffscreenCanvas(width, height);
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('lowdata: OffscreenCanvas 2D context is not available');
    ctx.drawImage(bitmap, 0, 0, width, height);
    bitmap.close();

    let quality = req.quality;
    let blob = await canvas.convertToBlob({ type: req.mimeType, quality });

    if (req.targetSizeKB) {
      const targetBytes = req.targetSizeKB * 1024;
      let iterations = 0;
      while (blob.size > targetBytes && quality > ${MIN_QUALITY} && iterations < ${MAX_QUALITY_ITERATIONS}) {
        quality = Math.max(${MIN_QUALITY}, quality - ${QUALITY_STEP});
        blob = await canvas.convertToBlob({ type: req.mimeType, quality });
        iterations++;
      }
    }

    self.postMessage({ requestId: req.requestId, ok: true, blob, width, height, sizeBytes: blob.size, quality });
  } catch (error) {
    self.postMessage({
      requestId: req.requestId,
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
};
`;

interface CompressionWorkerRequest {
  requestId: number;
  file: Blob;
  maxWidth: number;
  maxHeight?: number;
  mimeType: string;
  quality: number;
  targetSizeKB?: number;
}

type CompressionWorkerResponse =
  | {
      requestId: number;
      ok: true;
      blob: Blob;
      width: number;
      height: number;
      sizeBytes: number;
      quality: number;
    }
  | { requestId: number; ok: false; error: string };

let sharedWorker: Worker | undefined;
// Sticky, like the IndexedDB adapter's `db-open` failure: once the worker path has failed once
// (construction throws, or the worker itself crashes), stop retrying it for the rest of the
// session and always take the main-thread path instead — a CSP that blocks blob-URL workers, or a
// crashed OffscreenCanvas driver, isn't expected to start working again mid-session.
let workerUnavailable = false;
let nextRequestId = 0;
const pending = new Map<number, (response: CompressionWorkerResponse) => void>();

function supportsWorkerCompression(): boolean {
  return (
    !workerUnavailable &&
    typeof Worker !== 'undefined' &&
    typeof OffscreenCanvas !== 'undefined' &&
    typeof OffscreenCanvas.prototype.convertToBlob === 'function' &&
    typeof createImageBitmap !== 'undefined'
  );
}

function getOrCreateWorker(): Worker | undefined {
  if (sharedWorker) return sharedWorker;
  try {
    const blob = new Blob([WORKER_SOURCE], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const worker = new Worker(url);
    URL.revokeObjectURL(url); // safe once the Worker has been constructed from it

    worker.onmessage = (event: MessageEvent<CompressionWorkerResponse>) => {
      const resolve = pending.get(event.data.requestId);
      if (!resolve) return;
      pending.delete(event.data.requestId);
      resolve(event.data);
    };
    worker.onerror = () => {
      // The whole worker died — resolve every in-flight request as a failure (each caller then
      // falls open to the main thread) rather than hanging forever, and stop using this worker
      // path for the rest of the session. terminate() releases the crashed worker's thread
      // immediately rather than leaving it around (already-broken) until the page unloads.
      workerUnavailable = true;
      worker.terminate();
      for (const [id, resolve] of pending) {
        resolve({ requestId: id, ok: false, error: 'lowdata: compression worker crashed' });
      }
      pending.clear();
      sharedWorker = undefined;
    };

    sharedWorker = worker;
    return worker;
  } catch {
    workerUnavailable = true;
    return undefined;
  }
}

/**
 * Attempts the full compression pipeline off the main thread. Returns `undefined` on ANY failure
 * (feature detection false, worker construction/postMessage throws, the worker reports an error) —
 * callers must fail open to the existing main-thread path rather than propagate a rejection.
 */
export async function compressInWorker(
  file: Blob,
  request: {
    maxWidth: number;
    maxHeight?: number;
    mimeType: string;
    quality: number;
    targetSizeKB?: number;
  },
): Promise<CompressedImageResult | undefined> {
  if (!supportsWorkerCompression()) return undefined;
  const worker = getOrCreateWorker();
  if (!worker) return undefined;

  const requestId = nextRequestId++;
  const response = await new Promise<CompressionWorkerResponse>((resolve) => {
    pending.set(requestId, resolve);
    try {
      const message: CompressionWorkerRequest = { ...request, requestId, file };
      worker.postMessage(message);
    } catch {
      pending.delete(requestId);
      resolve({ requestId, ok: false, error: 'lowdata: failed to post to compression worker' });
    }
  });

  if (!response.ok) return undefined;
  return {
    blob: response.blob,
    width: response.width,
    height: response.height,
    sizeBytes: response.sizeBytes,
    quality: response.quality,
  };
}

/** Test-only escape hatch: resets the module-level shared-worker state between test cases. */
export function _resetCompressionWorkerForTests(): void {
  sharedWorker = undefined;
  workerUnavailable = false;
  nextRequestId = 0;
  pending.clear();
}
